query getMenu($name: String) {
  menu(name: $name) {
    items {
      order
      post_title
      object_type
      navitem {
        post_title
        post_name
      },
      navitemcategory {
        name
        slug
      }
      url
      children {
        order
        post_title
        object_type
        navitem {
          post_title
          post_name
          post_parent
        }
        navitemcategory {
        	name
        	slug
        }
      }
    }
  }
}
