query getPost($post: String){
  post(name:$post){
    id
    post_type
    post_title
    post_excerpt
    post_content
    post_date
    thumbnail
    author {
      user_nicename
      display_name
    }
  }
}
