query getPostsWithCategory($slug: String, $postType: String, $limit: Int, $skip: Int) {
  category(slug: $slug) {
    name
    posts(post_type: $postType, limit: $limit, skip: $skip) {
      id
      post_title
      post_name
      post_excerpt
      thumbnail
    }
    total_posts(post_type: $postType)
  }
  setting {
    defaultThumbnail
  }
}
